#!/usr/bin/env bash
# File: 4-TCP_and_UDP_ports

echo "Active Internet connections (only servers)"
netstat -tulnp 2>/dev/null | grep LISTEN

echo
echo "Active UNIX domain sockets (only servers)"
netstat -xlnp 2>/dev/null
