#!/bin/bash
# 4-TCP_and_UDP_ports

echo "Active Internet connections (only servers)"
sudo netstat -tulpn | grep LISTEN

echo "Active UNIX domain sockets (only servers)"
sudo netstat -lxpn | grep LISTEN
